name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: div-anh0901

      - name: Set up Node.js
        uses: div-anh0901
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test