name: Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: div-anh0901

      - name: Set up Node.js
        uses: div-anh0901
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Run vulnerability scan
        run: npm audit